something is wrong with the diffuser code

In [1]:
import optics_cuda
import cupy as cp
import matplotlib.pyplot as plt
import scattering
import numpy as np

source = optics_cuda.FatPencil(1,1,500,1,1)
size = 1000000
photons = source.make_photons(size)
print(photons.ez_x)
print(photons.ez_y)
print(photons.ez_z)

/home/joel/.local/lib/python3.10/site-packages/cupyx/jit/_interface.py:173: FutureWarning: cupyx.jit.rawkernel is experimental. The interface can change in the future.
  cupy._util.experimental('cupyx.jit.rawkernel')


[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 1. 1. ... 1. 1. 1.]


/home/joel/.local/lib/python3.10/site-packages/cupyx/jit/_interface.py:173: FutureWarning: cupyx.jit.rawkernel is experimental. The interface can change in the future.
  cupy._util.experimental('cupyx.jit.rawkernel')


In [2]:
diffuser = optics_cuda.AcryliteDiffuser()
phi = scattering.get_scattering_phi(size)
theta = diffuser._scattering.get_scattering_theta(size)
print(phi)
print(theta)

AttributeError: module 'optics_cuda' has no attribute 'AcryliteDiffuser'

In [ ]:
scattering.scatter((2,),(1024,),(photons.ez_x,photons.ez_y,photons.ez_z,theta,phi,int(size)))
print(photons.ez_x)
print(photons.ez_y)
print(photons.ez_z)

In [ ]:
h,b = cp.histogram(cp.arccos(photons.ez_z), 100)
fig = plt.figure(figsize=[15, 12])
ax = plt.subplot(projection='polar')
plt.plot(((b[:-1]+b[1:])/2).get(),h.get())

In [ ]:
x = diffuser._scattering.get_scattering_theta(10000)
h,b=cp.histogram(x,100)
fig = plt.figure(figsize=[15, 12])
ax = plt.subplot(projection='polar')
plt.plot(((b[:-1]+b[1:])/2).get(),h.get())

In [ ]:
diffuser.diffuse(photons)
print(photons.ez_x)
print(photons.ez_y)
print(photons.ez_z)

In [ ]:
photons = source.make_photons(1)
print(photons.ez_x)
print(photons.ez_y)
print(photons.ez_z)
theta = cp.full(1, np.pi/4, dtype=np.float32)
phi = cp.full(1, np.pi/2, dtype=np.float32)
size = np.int32(1)
scattering.scatter((1,),(1,),(photons.ez_x,photons.ez_y,photons.ez_z,theta,phi,size))
print(photons.ez_x)
print(photons.ez_y)
print(photons.ez_z)